# Generated by Django 5.0.6 on 2024-07-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=100)),
                ('year_formed', models.IntegerField()),
                ('popular_songs', models.CharField(max_length=250)),
                ('body', models.TextField(default='About Artist')),
            ],
        ),
    ]
